In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data.tsv', sep = '\t', header = None)

In [3]:
data.shape

(5241880, 5)

In [4]:
from tensorflow.python.keras.preprocessing.text import Tokenizer

In [6]:
tokenizer = Tokenizer()

In [16]:
tokenizer.fit_on_texts(data[1])

In [17]:
num_words = len(tokenizer.word_index)

In [18]:
num_words

3304013

In [19]:
x_train_tokens = tokenizer.texts_to_sequences(data[1])

In [21]:
import numpy as np
np.array(x_train_tokens[1])

array([   8,    3,    4, 1926])

In [23]:
num_tokens = [len(tokens) for tokens in x_train_tokens]
num_tokens = np.array(num_tokens)

In [24]:
np.mean(num_tokens)

5.97099132372355

In [25]:
np.max(num_tokens)

39

In [26]:
np.min(num_tokens)

1

In [27]:
#max token of length of the query should be
max_tokens = np.mean(num_tokens) + 2 * np.std(num_tokens)
max_tokens = int(max_tokens)
max_tokens

10

In [29]:
np.sum(num_tokens < max_tokens) / len(num_tokens)

0.9210664875960534

In [28]:
tokenizer2 = Tokenizer()
tokenizer2.fit_on_texts(data[2])

In [30]:
num_words = len(tokenizer2.word_index)
num_words

1387516

In [31]:
x_train_tokens2 = tokenizer2.texts_to_sequences(data[2])

In [32]:
np.array(x_train_tokens2[1])

array([  493,    54,     7,     3,  1064,   577,     2,    35,    47,
          26,   232,  1740,   307,  4870,    19,   237,   744,     4,
          89,  3597,  3438,   635,   487,  2077,    21, 25049,  1900,
           5, 37719,  2062,     6,   242,  2159,     1,   859])

In [33]:
num_tokens2 = [len(tokens) for tokens in x_train_tokens2]
num_tokens2 = np.array(num_tokens2)

In [34]:
num_tokens2

array([ 73,  35,  37, ...,  76,  96, 119])

In [36]:
np.mean(num_tokens2)

57.22629743527131

In [37]:
#max token of length of the passage should be
max_tokens2 = np.mean(num_tokens2) + 2 * np.std(num_tokens2)
max_tokens2 = int(max_tokens2)
max_tokens2

103

In [38]:
np.sum(num_tokens2 < max_tokens2) / len(num_tokens2)

0.9445380283409769